### ISSUE TITLE
Cant't extract Appimage file and deb file

### ISSUE THREAD

**Issue by zxp19821005** [deskaide/deskaide#209]
**Describe the bug**
I want to ported the program to Arch Linux,so I've writting 2 PKGBUILD file:
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname="deskaide-appimage"
pkgver=1.0.0.alpha.16
_pkgver=1.0.0-alpha.16
pkgrel=1
pkgdesc="An aide to your desk life!"
arch=('x86_64')
url="https://github.com/deskaide/deskaide"
license=('MIT')
options=(!strip)
conflicts=("${pkgname%-appimage}")
depends=('zlib' 'glibc')
_install_path="/opt/appimages"
source=("${pkgname%-appimage}-${pkgver}.AppImage::${url}/releases/tag/v${_pkgver}/Deskaide-${_pkgver}.AppImage"
    "LICENSE::https://raw.githubusercontent.com/deskaide/deskaide/develop/LICENSE")
sha256sums=('d3b04a754929890190d10a2280a72e95c5a4510e47dda26e2559e81855eab65d'
            '60fcc2fb41c30d5afc1767a98ddec84656bdd10e2f563c0fb11cba23c5cbc271')
prepare() {
    chmod a+x "${pkgname%-appimage}-${pkgver}.AppImage"
    "./${pkgname%-appimage}-${pkgver}.AppImage" --appimage-extract > /dev/null
    sed "s|Exec=${pkgname%-appimage}|Exec=${_install_path}/${pkgname%-appimage}.AppImage|g;s|${_appname}|${pkgname%-appimage}|g" -i "${srcdir}/squashfs-root/${_appname}.desktop"
}
package() {
    install -Dm755 "${srcdir}/${pkgname%-appimage}-${pkgver}.AppImage" "${pkgdir}/${_install_path}/${pkgname%-appimage}.AppImage"
    install -Dm644 "${srcdir}/squashfs-root/usr/share/icons/hicolor/256x256/apps/${_appname}.png" "${pkgdir}/usr/share/pixmaps/${pkgname%-appimage}.png"
    install -Dm644 "${srcdir}/squashfs-root/${_appname}.desktop" "${pkgdir}/usr/share/applications/${pkgname%-appimage}.desktop"
    sed "s|${_appname}|${pkgname%-appimage}|g" -i "${srcdir}/squashfs-root/usr/share/metainfo/${_appname}.appdata.xml"
    install -Dm644 "${srcdir}/squashfs-root/usr/share/metainfo/${_appname}.appdata.xml" "${pkgdir}/usr/share/metainfo/${pkgname%-appimage}.appdata.xml"
}
```
When I run `makepkg -f`,I got this error:
```
$ makepkg -f
==> 正在创建软件包：deskaide-appimage 1.0.0.alpha.16-1 (2023年06月07日 星期三 11时21分31秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 找到 deskaide-1.0.0.alpha.16.AppImage
  -> 找到 LICENSE
==> 正在验证 source 文件，使用sha256sums...
    deskaide-1.0.0.alpha.16.AppImage ... 通过
    LICENSE ... 通过
==> 正在释放源码...
==> 正在开始 prepare()...
./deskaide-1.0.0.alpha.16.AppImage:行8: 未预期的符号“newline”附近有语法错误
./deskaide-1.0.0.alpha.16.AppImage:行8: `<!DOCTYPE html>'
==> 错误： 在 prepare() 中发生一个错误。
    正在放弃...
```
When I directly executed the AppImage file,I got this:
```
$ ./deskaide-1.0.0.alpha.16.AppImage --appimage-extract
./deskaide-1.0.0.alpha.16.AppImage:行8: 未预期的符号“newline”附近有语法错误
./deskaide-1.0.0.alpha.16.AppImage:行8: `<!DOCTYPE html>'
```
So I writed a new PKGBUILD file to use the deb file as source:
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname="deskaide-bin"
pkgver=1.0.0.alpha.16
_pkgver=1.0.0-alpha.16
pkgrel=1
pkgdesc="An aide to your desk life!"
arch=('x86_64')
url="https://github.com/deskaide/deskaide"
license=('MIT')
options=(!strip)
conflicts=("${pkgname%-bin}")
depends=('zlib' 'glibc')
source=("${pkgname%-bin}-${pkgver}.deb::${url}/releases/tag/v${_pkgver}/${pkgname%-bin}_${pkgver}_amd64.deb"
    "LICENSE::https://raw.githubusercontent.com/deskaide/deskaide/develop/LICENSE")
sha256sums=('ecd7e7516af7893a3c712f75d72933f7bbd8f0dbe3d56c1e1abfcb6fa03ff108'
            '60fcc2fb41c30d5afc1767a98ddec84656bdd10e2f563c0fb11cba23c5cbc271')
package() {
    bsdtar -xf "${srcdir}/data.tar.xz" -C "${pkgdir}"
    install -Dm644 "${srcdir}/LICENSE" -t "${pkgdir}/usr/share/licenses/${pkgname}"
}
```
When I run `makepkg -f`,I got this:
```
$ makepkg -f
==> 正在创建软件包：deskaide-bin 1.0.0.alpha.16-1 (2023年06月07日 星期三 11时24分29秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 找到 deskaide-1.0.0.alpha.16.deb
  -> 找到 LICENSE
==> 正在验证 source 文件，使用sha256sums...
    deskaide-1.0.0.alpha.16.deb ... 通过
    LICENSE ... 通过
==> 正在释放源码...
==> 正在进入 fakeroot 环境...
==> 正在开始 package()...
bsdtar: Error opening archive: Failed to open '/home/zxp-endeavouros/.cache/paru/clone/deskaide-bin/src/data.tar.xz'
==> 错误： 在 package() 中发生一个错误。
    正在放弃...
```
When I try to extract the deb file,I got this:
```
$ ar -x deskaide-1.0.0.alpha.16.deb 
ar: deskaide-1.0.0.alpha.16.deb: file format not recognized
```
So I think are there someting wrong in these packages?

OS:EndeavourOS(Based on Arch Linux) 6.1.32-1-lts x86_64

**Comment by zxp19821005** [comment]
BTW,when I downloaded the newest release source https://github.com/deskaide/deskaide/archive/refs/tags/v1.0.0-alpha.16.tar.gz, it got well,but still have errors:
I run these command to build it:
```
yarn install
yarn build
yarn release
```
And I got these errors:
```
$ yarn release
yarn run v1.22.19
$ electron-builder --config .electron-builder.config.js --publish always
  • electron-builder  version=24.0.0 os=6.1.32-1-lts
  • loaded configuration  file=/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/.electron-builder.config.js
  • writing effective config  file=dist/builder-effective-config.yaml
  • executing @electron/rebuild  appDir=/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16 arch=x64
make: 进入目录“/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/leveldown/build”
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
../deps/leveldb/leveldb-1.20/util/hash.cc: In function ‘uint32_t leveldb::Hash(const char*, size_t, uint32_t)’:
../deps/leveldb/leveldb-1.20/util/hash.cc:37:9: 警告：this statement may fall through [-Wimplicit-fallthrough=]
   37 |       h += static_cast<unsigned char>(data[2]) << 16;
      |       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:39:5: 附注：here
   39 |     case 2:
      |     ^~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:40:9: 警告：this statement may fall through [-Wimplicit-fallthrough=]
   40 |       h += static_cast<unsigned char>(data[1]) << 8;
      |       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:42:5: 附注：here
   42 |     case 1:
      |     ^~~~
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
rm -f Release/obj.target/deps/leveldb/leveldb.a Release/obj.target/deps/leveldb/leveldb.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/leveldb/leveldb.a`
ar crs Release/obj.target/deps/leveldb/leveldb.a @Release/obj.target/deps/leveldb/leveldb.a.ar-file-list
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy/snappy.o
rm -f Release/obj.target/deps/snappy/snappy.a Release/obj.target/deps/snappy/snappy.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/snappy/snappy.a`
ar crs Release/obj.target/deps/snappy/snappy.a @Release/obj.target/deps/snappy/snappy.a.ar-file-list
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/binding.o
  SOLINK_MODULE(target) Release/obj.target/leveldown.node
  COPY Release/leveldown.node
make: 离开目录“/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/leveldown/build”
  • packaging       platform=linux arch=x64 electron=22.0.0 appOutDir=dist/linux-unpacked
  • skipping "afterSign" hook as no signing occurred, perhaps you intended "afterPack"?
  • building        target=AppImage arch=x64 file=dist/Deskaide-1.0.0-alpha.16.AppImage
  • building        target=deb arch=x64 file=dist/deskaide_1.0.0-alpha.16_amd64.deb
  • adding autoupdate files for: deb. (Beta feature)  resourceDir=/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/dist/linux-unpacked/resources
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:299:14)
    at PublishManager.getOrCreatePublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:218:19)
    at PublishManager.scheduleUpload (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:148:28)
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:198:14)

Error #2 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:299:14)
    at PublishManager.getOrCreatePublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:218:19)
    at PublishManager.scheduleUpload (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:148:28)
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:198:14)  failedTask=build stackTrace=Error: Cannot cleanup: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Error #1 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:299:14)
    at PublishManager.getOrCreatePublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:218:19)
    at PublishManager.scheduleUpload (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:148:28)
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:198:14)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Error #2 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:299:14)
    at PublishManager.getOrCreatePublisher (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:218:19)
    at PublishManager.scheduleUpload (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:148:28)
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:198:14)
    at throwError (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/builder-util/src/asyncTaskManager.ts:88:11)
    at checkErrors (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at AsyncTaskManager.awaitTasks (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/builder-util/src/asyncTaskManager.ts:58:5)
    at PublishManager.awaitTasks (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/publish/PublishManager.ts:232:28)
    at /home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/app-builder-lib/src/index.ts:114:32
    at executeFinally (/home/zxp-endeavouros/.cache/paru/clone/deskaide-1.0.0-alpha.16/node_modules/builder-util/src/promise.ts:23:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
But the appimage file and the deb file is generated well,and I can extract them.

**Comment by zxp19821005** [comment]
When I use `electron-builder --config .electron-builder.config.js --publish never` instead of `yarn release`,there was no error occured,and the AppImage file and deb file was generated,and can be extracted.

**Comment by zxp19821005** [comment]
Here is the link of AUR : https://aur.archlinux.org/packages/deskaide-appimage
If you have modified the `package.json` , please make a new version, Thank you!
